version: '3'
services:
  api1:
    container_name: api1
    build:
      context: ./API
      dockerfile: Dockerfile
    ports:
      - 5001:80
    depends_on:
      - db
      - loadbalancer
    networks:
      - backend

  api2:
    container_name: api2
    build:
      context: ./API
      dockerfile: Dockerfile
    ports:
      - 5002:80
    depends_on:
      - api1
    networks:
      - backend

  api3:
    container_name: api3
    build:
      context: ./API
      dockerfile: Dockerfile
    ports:
      - 5003:80
    depends_on:
      - api1
    networks:
      - backend

  loadbalancer:
    container_name: loadbalancer
    build:
      context: ./LoadBalancer
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - backend

  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: coffeeshop
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:


volumes:
  db-data:
